# This is a basic workflow to help you get started with Actions

name: Log commits

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Send Telegram message
        run: |
          commits='${{join(github.event.commits.*.message, '%0A- ')}}'
          curl \
            "https://api.telegram.org/bot1968842011:AAEHRUs_REm90S1S9E-tkwfG0g8vSX8K5OI/sendMessage" \
            -d 'chat_id=-1001513411956' \
            -d "text=<b>Nuovi cambiamenti!</b>%0A%0A- $commits" \
            -d 'parse_mode=html'

